- name: Authenticate Docker to GHCR
  hosts: azure_vm
  become: yes

  vars:
    github_user: Sadatul
    github_pat: pass

  tasks:
    - name: Docker login to GHCR
      become: yes
      become_user: azureuser
      ansible.builtin.command: docker login ghcr.io -u {{ github_user }} --password-stdin
      args:
        stdin: "{{ github_pat }}"
        executable: /bin/bash