name: Test and Build Backend

on:
  pull_request:
    branches:
        - main
  workflow_dispatch:

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      backend_changes: ${{ steps.backend_changes.outputs.backend_changes }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Check for changes in the backend folder
      id: backend_changes
      run: |
        git fetch origin main
        git fetch origin ${{ github.head_ref }}
        if git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -q '^backend/'; then
          echo "backend_changes=true" >> $GITHUB_OUTPUT
        else
          echo "backend_changes=false" >> $GITHUB_OUTPUT
        fi
  test:
    runs-on: ubuntu-latest
    needs: check_files
    if: ${{ needs.check_files.outputs.backend_changes == 'true' }}
    steps:
    - uses: actions/checkout@v4  
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Test with Maven
      run: |
        cd ./backend
        mvn test