name: Build and Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Version Name
        run: echo ${{ github.ref_name }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set Docker Tags
        id: set-tags
        run: |
          TAGS="ghcr.io/sadatul/mindtrace_backend:${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == *"RELEASE"* ]]; then
            TAGS="$TAGS,ghcr.io/sadatul/mindtrace_backend:latest"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: ${{ steps.set-tags.outputs.tags }}
          build-args: |
            profile=prod
          labels: |
            org.opencontainers.image.description=${{ github.event.release.body }}
          cache-from: type=gha
          cache-to: type=gha,mode=max