name: Build and Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Version Name
        run: echo ${{ github.ref_name }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: ghcr.io/sadatul/mindtrace_backend:${{ github.ref_name }}
          build-args: |
            profile=prod
          labels: |
            org.opencontainers.image.description=${{ github.event.release.body }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, 'RELEASE')
    needs:
      - build-and-push-image
    steps:
    - uses: actions/checkout@v4
    - name: create env file
      run: |
        echo "VERSION=${{ github.ref_name }}" >> ./envfile

    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: mindtrace
        file: infrastructure/docker/docker-stack.yml
        host: 4.216.184.149
        user: deployer
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        env_file: ./envfile
        registry_host: ghcr.io
        registry_user: ${{ github.actor }}
        registry_pass: ${{ secrets.REGISTRY_TOKEN }}