name: Test Frontend

on:
  pull_request:
    branches:
        - main
  workflow_dispatch:

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      frontend_changes: ${{ steps.frontend_changes.outputs.frontend_changes }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Check for changes in the frontend folder
      id: frontend_changes
      run: |
        git fetch origin main
        git fetch origin ${{ github.head_ref }}
        if git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -q '^frontend/'; then
          echo "frontend_changes=true" >> $GITHUB_OUTPUT
        else
          echo "frontend_changes=false" >> $GITHUB_OUTPUT
        fi
  test:
    runs-on: ubuntu-latest
    needs: check_files
    if: ${{ needs.check_files.outputs.frontend_changes == 'true' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Decode google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > ./frontend/app/google-services.json
    - name: Test with gradle
      run: |
        cd ./frontend
        ./gradlew test